// import './globals.css';
import './globals.css';

import type { Metadata } from 'next';

import { Urbanist } from 'next/font/google';

const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${urbanist.className} relative min-h-screen`}>
                {children}
            </body>
        </html>
    );
}
